$('#slider1').owlCarousel({
    loop:true,
    margin:10,
    responsiveClass:true,
    nav:true,
    responsive:{
        0:{
            items:1,
        },
        600:{
            items:2,
        },
        1000:{
            items:4,
        }
    }
});


$('#slider2').owlCarousel({
    loop:true,
    margin:10,
    responsiveClass:true,
    nav:true,
    responsive:{
        0:{
            items:1,
        },
        600:{
            items:1,
        },
        1000:{
            items:1,
        }
    }
});
